# dotnet code build

resources:
  repositories:
  - repository: self

variables:
  BuildConfiguration: release
  BuildPlatform: 'any cpu'
  dotNetCoreProjects: 'src/**/*.csproj'
  dotNetCorePublishProject: 'src/dfc-providerportal-findacourse/dfc-providerportal-findacourse.csproj'
  dotNetCoreTestProjects: '**/*[Tt]ests/*.csproj'

trigger:
  batch: true # batch if multiple checkins while build in progress
  branches:
    include:
    - master

pr:
  branches:
    include:
    - master

jobs:

# Full build
- job: BuildDotNetCore
  displayName: Build dot net core project
  pool:
    name: Continuous Integration 02 - SSD - 160ACU
    demands:
    - msbuild
    - visualstudio

  steps:

  # Zip up resources
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
      pathtoPublish: 'Resources'
      artifactName: resources

  # restore dependencies
  - task: DotNetCoreCLI@2
    displayName: 'dotnet restore'
    inputs:
      command: restore
      projects: $(dotNetCoreProjects)

  # build
  - task: DotNetCoreCLI@2
    displayName: 'dotnet build'
    inputs:
      command: build
      projects: $(dotNetCoreProjects)
      arguments: '--configuration $(BuildConfiguration)'

  # run unit tests
  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: test
      projects: $(dotNetCoreTestProjects)
      arguments: '--configuration $(BuildConfiguration)'
    continueOnError: true

  # publish 
  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      command: publish
      publishWebProjects: false
      projects: $(dotNetCorePublishProject)
      arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'

  # publish
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
      artifactName: dfc-providerportal-findacourse
